### ISSUE TITLE
Improve FileDriver - TableEngine

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1008]
H2GIS takes profit of the H2 TableEngine to link specific user data model stored in  a file.
This feature is used intensively by H2GIS users. It offers a nice wrapper to the H2 SQL engine, similar to the foreign-data wrapper in Postgresql. see in action with postgis https://github.com/pramsey/pgsql-ogr-fdw

Have a look here for the H2GIS File engine implementation https://github.com/orbisgis/h2gis/tree/master/h2gis-functions/src/main/java/org/h2gis/functions/io/file_table

The file drivers work well and users are happy to query a shapefile without loading it in the database.
However, the architecture of the file driver must be improved. Indeed, the following script

```sql
CALL FILE_TABLE('/tmp/myshapefile', 'geodata');
SELECT the_geom from geodata;
```
has the same impact than

```sql
SELECT * from geodata;
```
because the H2GIS file engine does not look at the list of columns requested. 
All values are always loaded
see https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/io/file_table/H2TableIndex.java#L91

This is problematic when input files contain many columns.

So we must find a way to retrieve the list of columns requested and return only the necessary values.

I have no idea how difficult the problem is and if it is a TableEngine or FileDriver limitation.

Therefore, we would first need the advice of experts from H2 database.

I am thinking about @katzyn who has helped us a lot to improve the geometry storage and syntax in H2.

**Comment by katzyn** [comment]
During execution on a query H2 either reads compete rows from the scan index, or only partial rows from some other index. For example, in the query `SELECT C1, C2 FROM TEST WHERE C1 = 100` in presence of an index on `(C1, C2)` columns only this index will be used, because it can be used to filter unnecessary rows (it has `C1` as a first column) and it has all other columns required by the query. If `C3` is also required, H2 will still use this index to reduce number of rows read, but complete rows will be read from the scan index to get values of `C3`. I don't think that you can really avoid reading of complete rows. You can try to add some index with common columns, however.

There are also table value functions, for example H2's own `CSVREAD()`, but they don't have any possibilities to limit the amount of data read.

**Comment by ebocher** [comment]
Thanks for answer.
Read all the values is an significant limitation because we regularly have files with several hundred columns.

**Comment by ebocher** [comment]
Dear @katzyn ,

I understand that the FunctionTable class  can't know the list of columns that can be requested in the select. 
We use massively FunctionTable and MVTable to load spatial driver with  files that can contains many columns. ShapeFile format is an example.
Do you think that  it's possible to find a workaround or extend the readTableFunction in H2 parser to set the column identifiers or is it definitely a no go possibility due to the complexity?

Bests

**Comment by nicolas-f** [comment]
We could overload Row in h2gis for reading data on a call to **getValue** https://github.com/h2database/h2database/blob/master/h2/src/main/org/h2/result/SearchRow.java#L63 ?

**Comment by katzyn** [comment]
`org.h2.index.Cursor` returned by indexes of your custom tables may return any implementations of `Row` and `SearchRow` from its `get()` and `getSearchRow()` methods and these rows may load data on demand. But you still will not have any information about used columns to prefetch their values. And if the first row from cursor was asked about values in columns 10, 5, and 6, for example, it doesn't mean that the next row will be asked for exactly the same columns. For example, the condition `WHERE A OR B` can read only the one column if second doesn't affect the result due to value of the first.

**Comment by ebocher** [comment]
@nicolas-f proposes to extend the FileDriver API in H2GIS with a method getCell(int row, int columnIndex) and extend defaultrow to return only the required value(s)

**Comment by ebocher** [comment]
@nicolas-f  any plan in your road map for this issue ?

**Comment by nicolas-f** [comment]
@ebocher I would like to be able to do this before the end of the month, but that would mean that I will have done two other higher priority tasks before then without other higher priority things happening in the meantime .

**Comment by ebocher** [comment]
@nicolas-f  Sure it's usually like this.
But you sounded it was trivial that's why I "re-ping" you

**Comment by ebocher** [comment]
Closed thanks to @nicolas-f
