### ISSUE TITLE
NullPointerException on ST_MakeValid.validGeom

### ISSUE THREAD

**Issue by jowko** [orbisgis/h2gis#1020]
I wanted to fix invalid geometry generated by another program: POLYGON ((5848 49987, 5848 49986, 5848 49984, 5848 49987)).
Calling ST_MakeValid.validGeom with one geometry results in an exception:
`
 java.lang.NullPointerException
	at org.h2gis.functions.spatial.clean.MakeValidOp.getArealGeometryFromLinearRing(MakeValidOp.java:537)
	at org.h2gis.functions.spatial.clean.MakeValidOp.nodePolygon(MakeValidOp.java:479)
	at org.h2gis.functions.spatial.clean.MakeValidOp.makePolygonValid(MakeValidOp.java:394)
	at org.h2gis.functions.spatial.clean.MakeValidOp.makeValid(MakeValidOp.java:155)
	at org.h2gis.functions.spatial.clean.ST_MakeValid.validGeom(ST_MakeValid.java:93)
	at org.h2gis.functions.spatial.clean.ST_MakeValid.validGeom(ST_MakeValid.java:58)
`

Here is sample code which can reproduce this error (geometry is created by jst_core):
[bug.zip](https://github.com/orbisgis/h2gis/files/3987498/bug.zip)

**Comment by SPalominos** [comment]
Thank you for the issue, we'll take a look.

**Comment by ebocher** [comment]
For a unit test

SELECT ST_MAKEVALID('POLYGON ((5848 49987, 5848 49986, 5848 49984, 5848 49987))'::GEOMETRY)

**Comment by ebocher** [comment]
PostGIS > 2.3

select st_makevalid('POLYGON ((5848 49987, 5848 49986, 5848 49984, 5848 49987))'::GEOMETRY)

returns

MULTILINESTRING ((5848 49987, 5848 49986), (5848 49986, 5848 49984))

Seems also wrong 

Proposal : 
In case of preserveGeomDim = true H2GIS must throw an error
In case of preserveGeomDim = false H2GIS  must returns 
MULTILINESTRING ((5848 49987, 5848 49986), (5848 49986, 5848 49984), (5848 49984, 5848 49987))

@mukoki  what is your opinion ?

**Comment by mukoki** [comment]
Flat polygons were not handled correctly by MakeValidOp.
I just committed a fix in OpenJUMP 👍 
https://sourceforge.net/p/jump-pilot/code/6225/
With this fix, the behaviour is a bit different than the on you propose : 
In case of preserveGeoDim = true : returns an empty Polygon. I think it is better because it will not interrupt the process of a large dataset containing a flat polygon. It is always possible to post-process the result to delete empty geometries. 
In case if preserveGeomDim = false : returns 
MULTILINESTRING ((5848 49986,5848 49987), (5848 49986,5848 49984))
Not sure what is the best answer in this case, but I think this one is as good as the one you proposed as it defines the same set of points (it completely covers the input geometry) with a simple geometry (no self-intersection).

**Comment by ebocher** [comment]
Hi OpenJump evangelist :-)
Thanks a lot

**Comment by SPalominos** [comment]
Fixed in the PR #1032
