### ISSUE TITLE
GeometryView coordinate dimension

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#1064]
```
drop table if exists test_dim;
create table test_dim (the_geom GEOMETRY(LINESTRINGZM, 4326));
insert into test_dim values(
		'SRID=4326;LINESTRINGZM(-43.23456 72.4567 0 0,-43.23456 72.4568 0 0)'::geometry);
```
must return 4 in coord_dimension column

**Comment by ebocher** [comment]
Since H2 supports the following signatures and new geometry dimensions. e.g 
```sql 
CREATE TABLE geo (the_geom GEOMETRY(POINTZ, 4326) 
```
It's not necessary to alter the table with the ST_COORDIM function as
```sql 
create table geo (the_geom GEOMETRY CHECK ST_COORDDIM(the_geom) = 3)
```
Consequentially, significant change are required in the method that creates the view GeometryColumn. See https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/factory/H2GISFunctions.java#L356
All constraint functions _GeometryTypeFromColumnType, _DimensionFromColumnType... must be checked.
In addition, certain uses such as 
```sql 
create table geo (the_geom GEOMETRY(POINTZ, 4326));
alter table geo add constraint zconstr CHECK ST_COORDDIM(the_geom) = 3
```
must be controlled.

@SPalominos @nicolas-f

**Comment by ebocher** [comment]
Other examples

```sql
ALTER TABLE geo
  ALTER COLUMN  the_geom TYPE geometry(POINTZ, 4326)
    USING ST_SetSRID(the_geom,2154);
```

**Comment by ebocher** [comment]
dear @katzyn,

It would be very interesting to have your point of view on the behaviour of constraint and using functions. 
Regards

**Comment by katzyn** [comment]
1. You definitely shouldn't add any own domain or check constraints that duplicate restrictions from data type of the column, each constraint slows down the things and complicates your schema and its transformations.

2. `ALTER TABLE … ALTER COLUMN … USING …` is a PostgreSQL-specific feature. It isn't supported by H2 1.4.200, but it is supported by current sources of H2. It obliviously throws an exception if geometry returned by this expression isn't compatible with new data type of the column.

```SQL
CREATE TABLE TEST(G GEOMETRY(POINTM, 10)) AS VALUES 'SRID=10;POINTM (1 2 2)';
> ok

TABLE TEST;
>> SRID=10;POINT M (1 2 2)

ALTER TABLE TEST ALTER COLUMN G SET DATA TYPE GEOMETRY(POINTM, 2)
    USING 'SRID=1' || SUBSTRING(G FROM POSITION(';', G));
> Check constraint violation: "(POINT M, 1) <> (POINT M, 2)"

ALTER TABLE TEST ALTER COLUMN G SET DATA TYPE GEOMETRY(POINT, 1)
    USING 'SRID=1' || SUBSTRING(G FROM POSITION(';', G));
> Check constraint violation: "(POINT M, 1) <> (POINT, 1)"

ALTER TABLE TEST ALTER COLUMN G SET DATA TYPE GEOMETRY(POINTM, 1)
    USING 'SRID=1' || SUBSTRING(G FROM POSITION(';', G));
> ok

TABLE TEST;
>> SRID=1;POINT M (1 2 2)
```
H2 throws error 23513 (check constraint violation) instead of expected 22018 (data conversion error) here; it looks like a minor bug. I can fix it if you prefer more clear error.

**Comment by ebocher** [comment]
Dear @katzyn ,
Great
We really appreciate your help. We will removed all  check constraints. It was an old workaround.
If you can return 22018 (data conversion error)  it'd be nice.
Regards

**Comment by ebocher** [comment]
Fixed
