### ISSUE TITLE
Check 2008 GeoJSON specification and RFC 7946 

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#813]
The 2008, RFC 7946  should be supported by the GeoJson driver. Depending on the changes, it would be nice to share the same code.

@gpbp, @SPalominos

**Comment by ebocher** [comment]
What is the final strategy about this issue ?

**Comment by SPalominos** [comment]
As the only change between `2008` and `RFC 7946` is the non supporting of the CRS, the same code can be shared. The only real problem is that the read part accepts `2008` and `RFC 7946` but the write part only `RFC 7946`.
 So, if the read geojoson is in `2008` and its CRS is `2000`, how is is written in the database? With its custom CRS or converted into `WGS84` (`RFC 7946`) ? And if it is written with its custom CRS, are the geometries converted into` WGS 84` on writing ?

**Comment by ebocher** [comment]
Is this issue fixed ?

**Comment by SPalominos** [comment]
@gpbp Did you have completely updated the geojson driver ?

**Comment by gpbp** [comment]
yes, it's solved
