### ISSUE TITLE
Pattern of timestamp type

### ISSUE THREAD

**Issue by gpbp** [orbisgis/h2gis#824]
Is there a pattern for all timestamp type?

**Comment by ebocher** [comment]
For what ?
Please explain a bit more the question ?

**Comment by nicolas-f** [comment]
I think it is in relation to the GeoJSON parsing. 

As I say, GeoJSON do not define any way to recognize a time or date, because this is not a type in this format. I do not recommend to check with a regex all attributes to attempt to recognize a date, because it will greatly slow down the parsing. So parse this GeoJSON field as text and then the user has to provide the right method to translate to time/date.

**Comment by gpbp** [comment]
ok, I'll just leave it be "VARCHAR". I'll close this issue from now.
