### ISSUE TITLE
Update to JTS 1.15.0

### ISSUE THREAD

**Issue by ebocher** [orbisgis/h2gis#865]
Because all JTS packages have been modified a new released must be planed for H2GIS , H2 database and all OrbisGIS tools.

**Comment by ebocher** [comment]
- [ ] postgis-jts-osgi
- [ ] postgis-jdbc
- [ ] postgis-jdbc-jtsparser

**Comment by gpetit** [comment]
Ok so we should just temporazise in order to give us time to finish some things (maybe till the end of the year ?)

**Comment by ebocher** [comment]
Sure. We will take time to do that

**Comment by ebocher** [comment]
Prepare the migration since the last change in H2 core https://github.com/h2database/h2database/pull/897
Thanks to @katzyn

**Comment by ebocher** [comment]
Here https://github.com/ebocher/H2GIS/tree/updateJTS1.15 the branch that updates H2 (to 1.4.197) and JTS (1.15).
Several tests do not work.

**Comment by ebocher** [comment]
@nicolas-f @SPalominos

**Comment by ebocher** [comment]
Move postgis-jts-osgi and postgis-jts to H2GIS repository ?

**Comment by nicolas-f** [comment]
If it facilitates compilation yes.

**Comment by ebocher** [comment]
and maintenance

**Comment by SPalominos** [comment]
For the error on several tests like `test_ST_MakeEnvelopeSRID()` in `org/h2gis/functions/spatial/create/CreateFunctionTest`, it comes from the  `((Geometry) rs.getObject(1))` instruction.
When it's called, H2 return a `copy` of the result geometry.
 - In JTS 1.14, the copy was create by calling `clone` which for a Geometry duplicates everything, including the SRID.
 - In JTS 1.15, the copy is created by calling `copy` which is abstract in Geometry and the implementing classes (like Polygon) copies all the attributes in a fresh new Geometry, except the SRID, which is get from the GeometryFactory.

**Comment by katzyn** [comment]
`Geometry.copy()` was used in H2 due to deprecation on `Geometry.clone()`.

BTW, `Polygon.clone()` is implemented as a call to `Polygon.copy()` anyway:
https://github.com/locationtech/jts/blob/3fb74b65e142bc166f58c9105f9dc43e911c7d72/modules/core/src/main/java/org/locationtech/jts/geom/Polygon.java#L355-L358

So usage of deprecated `clone()` does not make any difference for now.

**Comment by ebocher** [comment]
We must investigated because some of tests do not work.

**Comment by SPalominos** [comment]
@katzyn The problem does not come from H2, but from JTS.
The behaviour of `copy()`/`clone()` has changed between 1.14 and 1.15.
- In 1.14 : [`Polygon.clone()`](https://github.com/locationtech/jts/blob/5628f06392f727a15787123bb48c4af424cd85af/modules/core/src/main/java/org/locationtech/jts/geom/Polygon.java#L355) was calling [`Geometry.clone()`](https://github.com/locationtech/jts/blob/5628f06392f727a15787123bb48c4af424cd85af/modules/core/src/main/java/org/locationtech/jts/geom/Geometry.java#L1636) which was cloning/copying the whole Geometry, **including the SRID**.
 - In 1.15 : [`Polygon.copy()`](https://github.com/locationtech/jts/blob/3fb74b65e142bc166f58c9105f9dc43e911c7d72/modules/core/src/main/java/org/locationtech/jts/geom/Polygon.java#L366) overrides the abstract method `Geometry.copy()` and it copy/clone all the Geometry attributes **except the SRID**. The SRID of the newly created Geometry [comes from the `GeometryFactory` attribute](https://github.com/locationtech/jts/blob/3fb74b65e142bc166f58c9105f9dc43e911c7d72/modules/core/src/main/java/org/locationtech/jts/geom/Geometry.java#L202).

So a way for fixing the tests could be to sets the `GeometryFactory` SRID before creating the Geometry, instead of having a static final `GeometryFactory` [(like here)](https://github.com/orbisgis/h2gis/blob/master/h2gis-functions/src/main/java/org/h2gis/functions/spatial/create/ST_MakeEnvelope.java#L35).

**Comment by ebocher** [comment]
https://github.com/locationtech/jts/issues/273

**Comment by katzyn** [comment]
Did you read javadoc of `Geometry.setSRID()`? It looks like such behavior is expected. `setSRID()` should not be used in normal cases.

But overall logic in JTS does not look good, at least for situations where values with different factories with different SRID should be used. `WKBWriter` stores the SRID, not the factory. `WKBReader` reads the SRID and also not the factory, factory should be specified to `WKBReader` constructor.

If factory is not known or should not be known before reading such problem appears. On database side these is no normal way to set the factory. And client applications may even want to use different factories for different values, so connection-level setting does not help.

So for now on H2 side the only reasonable way to fix this issue is to set SRID on copied `Geometry` explicitly.
https://github.com/h2database/h2database/pull/1007

I hope this will fix this issue on H2 side.

H2GIS may also have the code that needs to be adjusted.

**Comment by ebocher** [comment]
@katzyn  thanks to point us that there is a javadoc for JTS !

However, as you write, the way the setSRID method works is not clear, especially in the case of the clone method. 

Regarding your fix, I think it would be good to add a test on a resultset object to be sure that the srid is well preserved , something like
ResultSet rs = stat.executeQuery("select * from geometryTable");
assertEquals( 4326,(Geometry)rs.getObject(1).getSrid())

**Comment by katzyn** [comment]
https://github.com/locationtech/jts/blob/3fb74b65e142bc166f58c9105f9dc43e911c7d72/modules/core/src/main/java/org/locationtech/jts/geom/Geometry.java#L264-L277
> SRIDs set using this method will _not_ be propagated to geometries returned by constructive methods.

Is `copy()` a “constructive” method? I don't know. It's javadoc, however, says that it returns a “full copy”. Yes, it's not clear how this should work.

Unfortunately, this problem was not found before release of H2 1.4.197. I use `GEOMETRY` data type in H2 but I do not use geometries with SRID values and I do not use H2GIS.

Test case with `ResultSet` will not test anything new, the same `ValueGeometry.getGeometry()` will be called. It even be from the cache and not from the disk in such simple test case.

**Comment by katzyn** [comment]
There is a bigger problem.

If geometry factory was created with a custom SRID and a geometry value was created by this factory this value will have that SRID form a factory and methods of this value will use it properly.

When this value is stored in database information about factory is not stored on disk. When such value is read from disk it will got the same SRID, but it's factory will be a default one without custom SRID. So this will be the same value with the same SRID, but it's “constructive” methods may work differently due to difference in factory. This may be not expected.

**Comment by katzyn** [comment]
It also looks like caching of geometry values in H2 works in such way that H2 may return a geometry with not only the default factory instead of original one but also with a some different factory if the same value with different factory was stored somewhere before. Cache do not distinguish values with the same WKB representation but with different factories. This looks weird enough. May be H2 should recreate value with some default factory before putting value in a cache to make results more predictable.

**Comment by katzyn** [comment]
Technically it's possible to return geometries from H2 not only with the same SRID and some random factory with unknown SRID, but also with a some factory with the same SRID. It's easy enough to read SRID from WKB to pass proper factory to WKBReader to ensure that value will have the factory with the same SRID. Other settings of a factory, however, will be default, because they are not stored in WKB.

This should be much better if application that works with database sets SRID values with factories as it expected by JTS. It this case methods of returned values should work properly.

But if application uses setSRID() on values passed to database this can make things worse.

So before doing such changes on H2 side we need to determine whether this needed by H2GIS or not.

**Comment by ebocher** [comment]
The fix proposed here https://github.com/orbisgis/jts/commit/974cd1e25f8a5aeb456e0c7af1f95631248278aa  will be in colliding with this PR https://github.com/h2database/h2database/commit/8097e478c5a2a357120a1ccb6d630b90dd9542f4.
The best solution is to use the copy method in H2 without patch and link a temporary version of JTS with the fixed we propose.
See on http://nexus.orbisgis.org/ -> 1.15.1-SNAPSHOT

@katzyn and @grandinj

**Comment by grandinj** [comment]
Not quite sure what you are suggestting? For H2 itself, why not just wait until all the right external stuff is deployed and then update our code and our dependencies.

**Comment by ebocher** [comment]
Thanks for the comments.
Sorry I wasn't very clear.
I understand Geometry.setSRID() is not a proper method for specifying of SRID according to JTS doc.
So instead of only reading geometry in getGeometryNoCopy a workaround has been added to get the SRID and set it using a fresh new factory. 
However, as the JTS developer writes here https://github.com/locationtech/jts/issues/273, all  fields in the Geometry object should be copied by the copy method (not only SRID).
So I think a good option will be to wait a fix on JTS. That's just my point of view.

**Comment by katzyn** [comment]
There was a workaround with `Geometry.setSRID()` in H2, but it was removed recently and replaced with a proper solution with a custom factory in the pull request that you mentioned. This implementation does not call `Geometry.setSRID()`, value from factory is used instead by JTS 1.15, fixed versions should use the same value from the source geometry instead with exactly the same result.

This solution works correctly with JTS 1.15 and should work correctly with your modified fork and with the next version of JTS when your fix will be merged to upstream project. So from point of view there is nothing to do with this issue on H2 side any more. Also there is no reason to require JTS > 1.15 for H2, but there may be a reason to require a more recent version for h2gis.

H2 should return values with predictable factories in ether way to avoid side effects in applications, older versions of H2 (including 1.4.197) can return a geometry object with any random factory due to possible cache poisoning. This was not good.

**Comment by ebocher** [comment]
@katzyn 
All the arguments make sense.
Thank you for your work on H2 that we enjoy every day.

**Comment by ebocher** [comment]
JTS 1.15.1  is out and available on Maven Central. It contains the "copy" fix .

@katzyn @grandinj 
What do you think about upgrading H2 with the new version of JTS ?

**Comment by katzyn** [comment]
Current development version of H2 should work fine with both 1.15 and 1.15.1. Tests with SRID are passed with both versions of JTS. It may be reasonable to require 1.15.1 for H2GIS, but I don't see a clear reason to require it for H2.

**Comment by ebocher** [comment]
The reason is quite simple  JTS 1.15.1 contains a bug fix.
I don't understand why you don't want to upgrade JTS?

**Comment by katzyn** [comment]
Are you talking about dependency in manifest or about exact version that is used for building and testing of H2?

H2 optionally requires 1.15.0 or any later version in MANIFEST.MF for OSGi environments and H2 can work with 1.15.0 and 1.15.1. Anyone who need more recent version can require it in own bundles. Do you see some problems with such requirement?

It's reasonable to upgrade dependency when incompatible changes arrived, like it was between 1.14 and 1.15 to avoid loading of incompatible library, but there are no incompatibilities between 1.15 and 1.15.1 in area that is used in H2. I don't see the reason to force users of H2 to upgrade JTS to 1.15.1 if they do not need more recent version.

**Comment by ebocher** [comment]
@SPalominos
